"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
lcm-gen 1.5.1
"""

from .ps4_controller_state_t import ps4_controller_state_t as ps4_controller_state_t
