"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ps4_controller_state_t(object):

    __slots__ = ["cross_x", "circle_o", "triangle", "square", "l1", "r1", "share", "options", "l3_left_stick_click", "r3_right_stick_click", "ps_button", "touchpad_click", "left_stick_horizontal", "left_stick_vertical", "right_stick_horizontal", "right_stick_vertical", "l2_trigger", "r2_trigger", "dpad_horizontal", "dpad_vertical"]

    __typenames__ = ["boolean", "boolean", "boolean", "boolean", "boolean", "boolean", "boolean", "boolean", "boolean", "boolean", "boolean", "boolean", "int16_t", "int16_t", "int16_t", "int16_t", "int16_t", "int16_t", "int16_t", "int16_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.cross_x = False
        """
        Button states: A mapping of buttons (True = pressed, False = not pressed)
        LCM Type: boolean
        """

        self.circle_o = False
        """
        Cross (X)
        LCM Type: boolean
        """

        self.triangle = False
        """
        Circle (O)
        LCM Type: boolean
        """

        self.square = False
        """
        Triangle
        LCM Type: boolean
        """

        self.l1 = False
        """
        Square
        LCM Type: boolean
        """

        self.r1 = False
        """
        L1
        LCM Type: boolean
        """

        self.share = False
        """
        R1
        LCM Type: boolean
        """

        self.options = False
        """
        Share
        LCM Type: boolean
        """

        self.l3_left_stick_click = False
        """
        Options
        LCM Type: boolean
        """

        self.r3_right_stick_click = False
        """
        L3 (Left Stick Click)
        LCM Type: boolean
        """

        self.ps_button = False
        """
        R3 (Right Stick Click)
        LCM Type: boolean
        """

        self.touchpad_click = False
        """
        PS Button
        LCM Type: boolean
        """

        self.left_stick_horizontal = 0
        """
        Touchpad Click
        Axis states: Ranges from 0 to 255, where 128 is neutral
        LCM Type: int16_t
        """

        self.left_stick_vertical = 0
        """
        Left Stick Horizontal (0 - 255, neutral at 128)
        LCM Type: int16_t
        """

        self.right_stick_horizontal = 0
        """
        Left Stick Vertical (0 - 255, neutral at 128)
        LCM Type: int16_t
        """

        self.right_stick_vertical = 0
        """
        Right Stick Horizontal (0 - 255, neutral at 128)
        LCM Type: int16_t
        """

        self.l2_trigger = 0
        """
        Right Stick Vertical (0 - 255, neutral at 128)
        LCM Type: int16_t
        """

        self.r2_trigger = 0
        """
        L2 Trigger (0 - 255, neutral at 128)
        LCM Type: int16_t
        """

        self.dpad_horizontal = 0
        """
        R2 Trigger (0 - 255, neutral at 128)
        LCM Type: int16_t
        """

        self.dpad_vertical = 0
        """
        D-Pad Horizontal (0 - 255, neutral at 128)
        LCM Type: int16_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(ps4_controller_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbbbbbbbbbbbhhhhhhhh", self.cross_x, self.circle_o, self.triangle, self.square, self.l1, self.r1, self.share, self.options, self.l3_left_stick_click, self.r3_right_stick_click, self.ps_button, self.touchpad_click, self.left_stick_horizontal, self.left_stick_vertical, self.right_stick_horizontal, self.right_stick_vertical, self.l2_trigger, self.r2_trigger, self.dpad_horizontal, self.dpad_vertical))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ps4_controller_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ps4_controller_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ps4_controller_state_t()
        self.cross_x = bool(struct.unpack('b', buf.read(1))[0])
        self.circle_o = bool(struct.unpack('b', buf.read(1))[0])
        self.triangle = bool(struct.unpack('b', buf.read(1))[0])
        self.square = bool(struct.unpack('b', buf.read(1))[0])
        self.l1 = bool(struct.unpack('b', buf.read(1))[0])
        self.r1 = bool(struct.unpack('b', buf.read(1))[0])
        self.share = bool(struct.unpack('b', buf.read(1))[0])
        self.options = bool(struct.unpack('b', buf.read(1))[0])
        self.l3_left_stick_click = bool(struct.unpack('b', buf.read(1))[0])
        self.r3_right_stick_click = bool(struct.unpack('b', buf.read(1))[0])
        self.ps_button = bool(struct.unpack('b', buf.read(1))[0])
        self.touchpad_click = bool(struct.unpack('b', buf.read(1))[0])
        self.left_stick_horizontal, self.left_stick_vertical, self.right_stick_horizontal, self.right_stick_vertical, self.l2_trigger, self.r2_trigger, self.dpad_horizontal, self.dpad_vertical = struct.unpack(">hhhhhhhh", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ps4_controller_state_t in parents: return 0
        tmphash = (0x909094f3046534d4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ps4_controller_state_t._packed_fingerprint is None:
            ps4_controller_state_t._packed_fingerprint = struct.pack(">Q", ps4_controller_state_t._get_hash_recursive([]))
        return ps4_controller_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ps4_controller_state_t._get_packed_fingerprint())[0]

